Added the code from my project
The part that's not working is in the method 'connect'.

I've got JDK 11.0.2 which apparently doesn't require you to use Class.forName("com.mysql.cj.jdbc.Driver"); (or Class.forName("com.mysql.jdbc.Driver");) anymore.

I've downloaded what I think is the latest JDBC JConnector and added it to the referenced libraries - I'll attempt to upload screenshots showing this.

The error I get is as follows:

Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
java.sql.SQLException: No suitable driver found for jdbc.mysql://localhost:3306/swingtest
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at model.DataBase.connect(DataBase.java:46)
	at model.test.main(test.java:9)